# Generated by Django 3.2 on 2021-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='firstfive',
            field=models.CharField(default='b', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lastfive',
            field=models.CharField(default='e', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='remark',
            field=models.CharField(default='Architect', max_length=200),
        ),
    ]
