# Generated by Django 3.2 on 2021-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210501_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.CharField(default='nishant', max_length=200),
        ),
    ]
